title: The Butler
baseline: Create your blog in 1 minute!
description: The Butler is a ready to use starter blog, powered by Cecil, your content driven static site generator.
baseurl: https://the-butler.cecil.app/
image: /cecil-preview.png
buttons:
  - name: Netlify
    url: https://cecil.app/hosting/netlify/deploy
    image: https://www.netlify.com/img/deploy/button.svg
  - name: Forestry
    url: https://cecil.app/cms/forestry/import
    image: https://assets.forestry.io/import-to-forestryK.svg
source: https://github.com/Cecilapp/the-butler
screenshot: /cecil-preview.png
demo: https://the-butler-demo.cecil.app
