title: The Butler
baseline: Create a blog in 1 minute!
description: The Butler is a ready to use static blog, powered by Cecil.
baseurl: https://the-butler.cecil.app/
demo: https://the-butler-demo.cecil.app
source: https://github.com/Cecilapp/the-butler
