title: The Butler
baseline: Create your blog in 1 minute!
description: The Butler is a ready to use starter blog, powered by Cecil, your content driven static site generator.
baseurl: https://the-butler.cecil.app/
image: cecil-preview.png
theme:
  - applanding
  - netlify
applanding:
  buttons:
    - name: Netlify
      url: https://cecil.app/hosting/netlify/deploy
      image: https://www.netlify.com/img/deploy/button.svg
    - name: Vercel
      url: https://cecil.app/hosting/vercel/deploy
      image: https://vercel.com/button/default.svg
    - name: Forestry
      url: https://cecil.app/cms/forestry/import
      image: https://assets.forestry.io/import-to-forestryK.svg
  source: https://github.com/Cecilapp/the-butler
  documentation: https://github.com/Cecilapp/the-butler#readme
  screenshot: cecil-preview.png
  demo: https://the-butler-demo.cecil.app
netlify:
  redirects:
    - from: https://the-butler.netlify.app/*
      to: https://the-butler-demo.cecil.app/:splat
      status: 301
      force: true
